CREATE DATABASE temp_schema;

USE TEMP_SCHEMA;

-- CREATE tables
CREATE TABLE TABLE1 (COL_STRING VARCHAR(255), COL_NUM INT, COL_DATE DATE);
ALTER TABLE TABLE1 MODIFY COLUMN COL_NUM NUMERIC(10, 2);
CREATE TABLE TABLE2 (COL_STRING VARCHAR(255), COL_NUM NUMERIC(10, 2), COL_DATE DATE);
CREATE TABLE TABLE3 (COL_DATE DATE, COL_STRING VARCHAR(255), COL_NUM NUMERIC(10, 2));

-- simple insert command 
INSERT INTO TABLE1 (COL_STRING, COL_NUM, COL_DATE) VALUES 
('Alice', 101, '2024-01-15'),
('Bob', 202, '2023-12-10'),
('Charlie', 303, '2022-05-25'),
('David', 404, '2021-08-30'),
('Eve', 505, '2020-11-05');

-- insert command with select 
INSERT INTO TABLE2 SELECT * FROM TABLE1;

-- INSERT COMMAND WITH SHUFFLED COLUMN SELECT
INSERT INTO TABLE3 SELECT COL_DATE, COL_STRING, COL_NUM FROM TABLE2; 

SELECT * FROM TABLE1;
SELECT *FROM TABLE2;
SELECT * FROM TABLE3;

