/*
SELECT COLMN(s)
FROM TABLE
ORDER BY COLUMN(s) ASC | DESC
LIMIT [start_index,] length
*/ 

SELECT * FROM COUNTRIES;
SELECT * FROM COUNTRIES LIMIT 10;
SELECT * FROM COUNTRIES LIMIT 10, 10;  -- FROM 10th row, print next 10 columns except the 10th column
SELECT * FROM COUNTRIES LIMIT 20, 5;