SELECT * FROM COUNTRIES.COUNTRIES
	WHERE POPULATION > 200000000
    ORDER BY POPULATION DESC;
    
SELECT * FROM HR.EMP 
	WHERE COMM IS NOT NULL
    ORDER BY COMM;

SELECT * FROM CUSTOMER_ORDERS.ORDER_ITEMS
	WHERE QUANTITY > 4 AND UNIT_PRICE > 49;
	